spring:
  application:
    name: core
  data:
    mongodb:
      uri: mongodb://localhost:27017/main
  cloud:
    openfeign:
      okhttp:
        enabled: true
  task:
    scheduling:
      pool:
        size: 5
      thread-name-prefix: scheduled-task-

server:
  port: 7778
  error:
    include-stacktrace: always

# Выносим настройки сюда
getgems:
  api-key: "1767696328881-mainnet-10772317-r-JZxQ9TmGu7URUGscDZjznrMzVtNBcCpVlOTgsFx9t8Xv8c4o"
  proxy:
    host: "127.0.0.1"
    port: 8000
    enabled: true

logging:
  level:
    com.ceawse.blinkgift: INFO