spring:
  application:
    name: core
  data:
    mongodb:
      uri: mongodb://localhost:27017/main
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false
  task:
    scheduling:
      pool:
        size: 5  # Укажи число, достаточное для всех твоих @Scheduled задач
      thread-name-prefix: scheduled-task-

server:
  port: 7778
  error:
    include-stacktrace: always

logging:
  level:
    com.ceawse.blinkgift: INFO
    org.springframework.web: INFO
    org.apache.coyote: INFO

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic