spring:
  application:
    name: core-processor
  data:
    mongodb:
      uri: mongodb://localhost:27017/main
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        enabled: false

server:
  port: 7779
  error:
    include-stacktrace: always

logging:
  level:
    root: INFO
    com.ceawse.coreprocessor: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.web: INFO
    org.apache.coyote: INFO